export type UIStyleGroup = "button" | "bubble" | "label" | "panel";

export type UIStylePropValue = string | number | boolean;

export type UIStyleEntry = {
  id: string;
  group: UIStyleGroup;
  title: string;
  description: string;
  usedIn: string[];
  sourcePath: string;
  similarityKey: string;
  propsSummary: Record<string, UIStylePropValue>;
  previewKind: string;
  deprecated?: boolean;
};

export const UI_STYLE_GROUP_LABELS: Record<UIStyleGroup, string> = {
  button: "Buttons",
  bubble: "Bubbles",
  label: "Labels",
  panel: "Panels",
};

export const UI_STYLE_REGISTRY: UIStyleEntry[] = [
  {
    id: "button.timeline-auth-primary",
    group: "button",
    title: "Primary auth action",
    description: "Главная CTA-кнопка в auth panel и других позитивных сценариях desktop shell.",
    usedIn: ["Timeline", "Auth panel", "Desktop"],
    sourcePath: "apps/web/src/pages/TimelinePage.tsx",
    similarityKey: "button-primary-desktop",
    propsSummary: {
      className: "btn",
      emphasis: "primary",
      tone: "gradient",
      radius: "12-14px",
    },
    previewKind: "button-primary",
  },
  {
    id: "button.timeline-auth-ghost",
    group: "button",
    title: "Ghost utility action",
    description: "Вторичная desktop-кнопка для admin/auth/tooling действий без плотной заливки.",
    usedIn: ["Timeline", "Auth panel", "Desktop"],
    sourcePath: "apps/web/src/pages/TimelinePage.tsx",
    similarityKey: "button-ghost-desktop",
    propsSummary: {
      className: "btn btnGhost",
      emphasis: "secondary",
      tone: "ghost",
      radius: "12-14px",
    },
    previewKind: "button-ghost",
  },
  {
    id: "button.miniapp-primary",
    group: "button",
    title: "Mini App primary button",
    description: "Базовая mobile-first action button в Mini App shell и profile/actions surface.",
    usedIn: ["Mini App", "Profile", "Mobile"],
    sourcePath: "apps/web/src/components/miniapp/AuthStatusPanelCompact.tsx",
    similarityKey: "button-primary-mobile",
    propsSummary: {
      className: "miniAppButton",
      emphasis: "primary",
      tone: "solid-dark",
      radius: "14px",
    },
    previewKind: "miniapp-primary",
  },
  {
    id: "button.miniapp-group-toggle",
    group: "button",
    title: "Mini App group toggle",
    description: "Широкая строка-переключатель секции с бейджем количества и открытым состоянием.",
    usedIn: ["Mini App", "Task list", "Mobile"],
    sourcePath: "apps/web/src/components/miniapp/MobileTaskList.tsx",
    similarityKey: "button-toggle-mobile",
    propsSummary: {
      className: "miniAppTaskGroupToggle",
      behavior: "toggle-row",
      tone: "section-header",
      radius: "0 / inherited",
    },
    previewKind: "miniapp-group-toggle",
  },
  {
    id: "button.attachment-icon-actions",
    group: "button",
    title: "Attachment icon actions",
    description: "Компактные icon-only действия у вложений: просмотр, скачивание, удаление.",
    usedIn: ["Attachments", "Task drawer", "Desktop"],
    sourcePath: "apps/web/src/components/attachments/TaskAttachmentsSection.tsx",
    similarityKey: "button-icon-compact",
    propsSummary: {
      className: "attachmentActionIconButton",
      behavior: "icon-only",
      tone: "compact-tools",
      radius: "14px",
    },
    previewKind: "attachment-actions",
  },
  {
    id: "button.admin-tab-header",
    group: "button",
    title: "Admin tab header",
    description: "Кнопка-заголовок вкладки в админке для верхнего и вложенного уровней навигации.",
    usedIn: ["Admin", "Tabs", "Desktop"],
    sourcePath: "apps/web/src/pages/AdminPage.tsx",
    similarityKey: "button-nav-tab",
    propsSummary: {
      className: "adminTabButton",
      behavior: "tab-header",
      tone: "textual-nav",
      radius: "0",
    },
    previewKind: "admin-tab",
  },
  {
    id: "bubble.default-badge",
    group: "bubble",
    title: "Default badge",
    description: "Базовый gradient badge, который живёт в timeline, drawer, designers board и tooltip.",
    usedIn: ["Timeline", "Drawer", "Designers", "Desktop"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "bubble-pill-default",
    propsSummary: {
      className: "badge",
      tone: "default-gradient",
      shape: "pill",
      density: "compact",
    },
    previewKind: "badge-default",
  },
  {
    id: "bubble.drawer-date-badge",
    group: "bubble",
    title: "Drawer date badge",
    description: "Компактный badge для дат milestone в карточке задачи.",
    usedIn: ["Task drawer", "Milestones", "Desktop"],
    sourcePath: "apps/web/src/components/TaskDetailsDrawer.tsx",
    similarityKey: "bubble-pill-date",
    propsSummary: {
      className: "badge drawerDateBadge",
      tone: "date",
      shape: "pill",
      density: "compact",
    },
    previewKind: "badge-date",
  },
  {
    id: "bubble.admin-count-badge",
    group: "bubble",
    title: "Admin count badge",
    description: "Счётчик в админке для числа ссылок, элементов и других summary-метрик.",
    usedIn: ["Admin", "Summary", "Desktop"],
    sourcePath: "apps/web/src/pages/AdminPage.tsx",
    similarityKey: "bubble-pill-count",
    propsSummary: {
      className: "adminCountBadge",
      tone: "mint-summary",
      shape: "pill",
      density: "compact",
    },
    previewKind: "admin-count",
  },
  {
    id: "bubble.admin-link-status",
    group: "bubble",
    title: "Access-link status badge",
    description: "Статус временной ссылки с цветовыми вариантами active / expired / revoked.",
    usedIn: ["Admin", "Access links", "Desktop"],
    sourcePath: "apps/web/src/pages/AdminPage.tsx",
    similarityKey: "bubble-pill-status",
    propsSummary: {
      className: "adminLinkStatusBadge",
      tone: "status-variant",
      shape: "pill",
      density: "compact",
    },
    previewKind: "admin-link-status",
  },
  {
    id: "bubble.miniapp-due",
    group: "bubble",
    title: "Mini App due bubble",
    description: "Правый bubble со сроком в компактной мобильной карточке задачи.",
    usedIn: ["Mini App", "Task list", "Mobile"],
    sourcePath: "apps/web/src/components/miniapp/MobileTaskList.tsx",
    similarityKey: "bubble-pill-mobile-date",
    propsSummary: {
      className: "miniAppTaskDueBubble",
      tone: "mobile-date",
      shape: "pill",
      density: "compact",
    },
    previewKind: "miniapp-due",
  },
  {
    id: "bubble.attachment-count",
    group: "bubble",
    title: "Attachment count badge",
    description: "Бейдж количества вложений в свёрнутой панели attachments.",
    usedIn: ["Attachments", "Task drawer", "Desktop"],
    sourcePath: "apps/web/src/components/attachments/TaskAttachmentsSection.tsx",
    similarityKey: "bubble-pill-count-compact",
    propsSummary: {
      className: "badge attachmentCountBadge",
      tone: "count",
      shape: "pill",
      density: "micro",
    },
    previewKind: "attachment-count",
  },
  {
    id: "label.page-title",
    group: "label",
    title: "Page title",
    description: "Сильный заголовок страницы или крупного блока, встречается на desktop и в админке.",
    usedIn: ["Timeline", "Admin", "Desktop"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "label-heading-primary",
    propsSummary: {
      className: "pageTitle",
      weight: 800,
      size: "20-24px",
      tone: "strong",
    },
    previewKind: "label-title",
  },
  {
    id: "label.muted-meta",
    group: "label",
    title: "Muted metadata",
    description: "Приглушённый служебный текст для описаний, подсказок, аудита и secondary copy.",
    usedIn: ["Global", "Cards", "Admin", "Workbench"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "label-meta-muted",
    propsSummary: {
      className: "muted",
      weight: 500,
      size: "12-14px",
      tone: "muted",
    },
    previewKind: "label-muted",
  },
  {
    id: "label.miniapp-task-title",
    group: "label",
    title: "Mini App task title",
    description: "Сильное mobile-first имя задачи внутри карточки и agenda surfaces.",
    usedIn: ["Mini App", "Cards", "Mobile"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "label-title-mobile",
    propsSummary: {
      className: "miniAppTaskTitle",
      weight: 700,
      size: "16px",
      tone: "strong",
    },
    previewKind: "label-miniapp-title",
  },
  {
    id: "label.drawer-section-title",
    group: "label",
    title: "Drawer section title",
    description: "Заголовок вложенного блока в карточке задачи и attachment panel.",
    usedIn: ["Task drawer", "Attachments", "Desktop"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "label-section-subtitle",
    propsSummary: {
      className: "drawerSectionTitle",
      weight: 800,
      size: "15-16px",
      tone: "section",
    },
    previewKind: "label-drawer-section",
  },
  {
    id: "label.designer-column-name",
    group: "label",
    title: "Designer column name",
    description: "Двухстрочное имя дизайнера в заголовке колонки board view.",
    usedIn: ["Designers", "Board", "Desktop"],
    sourcePath: "apps/web/src/components/DesignersBoard.tsx",
    similarityKey: "label-title-board",
    propsSummary: {
      className: "designerColumnName",
      weight: 800,
      size: "14-16px",
      tone: "board-heading",
    },
    previewKind: "label-designer-name",
  },
  {
    id: "panel.global-card",
    group: "panel",
    title: "Global glass card",
    description: "Основная card surface проекта с общим градиентом, blur и material shadow.",
    usedIn: ["Global", "Timeline", "Admin", "Desktop"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "panel-root-card",
    propsSummary: {
      className: "card",
      radius: "20px",
      tone: "glass",
      shadow: "material",
    },
    previewKind: "panel-card",
  },
  {
    id: "panel.drawer-section",
    group: "panel",
    title: "Drawer section card",
    description: "Вложенная surface внутри карточки задачи для timing, calendar, notes и attachments.",
    usedIn: ["Task drawer", "Desktop"],
    sourcePath: "apps/web/src/components/TaskDetailsDrawer.tsx",
    similarityKey: "panel-nested-drawer",
    propsSummary: {
      className: "card drawerSection",
      radius: "18-20px",
      tone: "nested",
      shadow: "soft",
    },
    previewKind: "panel-drawer",
  },
  {
    id: "panel.designers-task-card",
    group: "panel",
    title: "Designers board task card",
    description: "Узкая цветовая карточка задачи в борде дизайнеров.",
    usedIn: ["Designers", "Board", "Desktop"],
    sourcePath: "apps/web/src/components/DesignersBoard.tsx",
    similarityKey: "panel-card-board",
    propsSummary: {
      className: "designerTaskCard",
      radius: "16-18px",
      tone: "palette-tinted",
      shadow: "soft",
    },
    previewKind: "panel-designer-task",
  },
  {
    id: "panel.miniapp-task-card",
    group: "panel",
    title: "Mini App task card",
    description: "Основная мобильная карточка задачи и agenda item с мягкой dark surface.",
    usedIn: ["Mini App", "Task list", "Agenda", "Mobile"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "panel-card-mobile",
    propsSummary: {
      className: "miniAppTaskCard",
      radius: "18px",
      tone: "mobile-dark",
      shadow: "soft",
    },
    previewKind: "panel-miniapp-task",
  },
  {
    id: "panel.admin-access-link",
    group: "panel",
    title: "Admin access-link card",
    description: "Операторская карточка временной ссылки с метаданными, кнопками и журналом.",
    usedIn: ["Admin", "Access links", "Desktop"],
    sourcePath: "apps/web/src/pages/AdminPage.tsx",
    similarityKey: "panel-card-admin",
    propsSummary: {
      className: "adminAccessLinkCard",
      radius: "16px",
      tone: "admin-surface",
      shadow: "soft",
    },
    previewKind: "panel-admin-link",
  },
  {
    id: "panel.workbench-surface",
    group: "panel",
    title: "Workbench floating surface",
    description: "Плавающая служебная панель крутилок с blur и отдельным material language.",
    usedIn: ["Workbench", "Desktop"],
    sourcePath: "apps/web/src/styles/globals.css",
    similarityKey: "panel-floating-workbench",
    propsSummary: {
      className: "workbenchBody",
      radius: "14px",
      tone: "floating-glass",
      shadow: "elevated",
    },
    previewKind: "panel-workbench",
  },
];
